/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Model.conectar;
import Model.usuarioActual;
import java.awt.List;
import java.awt.event.KeyEvent;
import java.lang.reflect.Array;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * La clase `LoginManager` proporciona métodos para gestionar el inicio de sesión de usuarios.
 * Esta clase incluye un método para verificar las credenciales de usuario y abrir la interfaz de usuario principal si el inicio de sesión es exitoso.
 * 
 * Esta clase depende de la clase `conectar` para establecer la conexión a la base de datos y de la clase `usuarioActual` para almacenar el nombre de usuario actual.
 * 
 * @author mmarc
 */

public class loginApp extends javax.swing.JFrame {

    /**
     * Creates new form loginApp
     */
    public loginApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginText = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 350));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.control);
        setPreferredSize(new java.awt.Dimension(400, 350));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginText.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        loginText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextActionPerformed(evt);
            }
        });
        getContentPane().add(loginText, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 72, 237, -1));

        passField.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 144, 237, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel3.setText("Login");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 75, 41, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 147, 69, -1));

        enterButton.setBackground(new java.awt.Color(102, 102, 255));
        enterButton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        enterButton.setForeground(new java.awt.Color(255, 255, 255));
        enterButton.setText("Entrar");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        enterButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                enterButtonKeyTyped(evt);
            }
        });
        getContentPane().add(enterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 174, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTextActionPerformed

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed

        // TODO add your handling code here:
        entrada();


    }//GEN-LAST:event_enterButtonActionPerformed

    private void enterButtonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterButtonKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {

            entrada();

        }

    }//GEN-LAST:event_enterButtonKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField loginText;
    private javax.swing.JPasswordField passField;
    // End of variables declaration//GEN-END:variables

   
    /** El nombre de usuario introducido en el campo de texto de inicio de sesión. */
    String log;
    
    /** La contraseña introducida en el campo de contraseña de inicio de sesión. */
    String pass;

    /**
     * Verifica las credenciales del usuario y permite el acceso si son válidas.
     */
    public void entrada() {
        // Conectar a la base de datos
        conectar.conecta();
        
        // Obtener el nombre de usuario introducido en el campo de texto
        usuarioActual.nombre = loginText.getText();
        log = usuarioActual.nombre;

        // Obtener la contraseña introducida en el campo de contraseña
        pass = new String(passField.getPassword());

        // Verificar las credenciales del usuario
        if (conectar.loginUsuario(log, pass)) {
            // Cerrar la conexión a la base de datos
            conectar.cerrarConexion();
            
            // Abrir la interfaz de usuario principal
            Vista.Seleccion sl = new Vista.Seleccion();
            sl.setVisible(true);
            
            // Cerrar la ventana de inicio de sesión actual
            this.dispose();
        } else {
            // Mostrar un mensaje de error si la contraseña es incorrecta
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
            
            // Limpiar los campos de texto de inicio de sesión
            loginText.setText("");
            passField.setText("");
        }
    }
}



