/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Vista.nuevoProducto;

import Vista.nuevoProducto;

import Model.*;
import Model.conectar;
import Model.conectar.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.ListModel;

import javax.swing.event.ListSelectionEvent;


/**
 * /**
 * Clase Seleccion que representa la ventana de selección de opciones.
 
 *
 * @author mmarc
 */


public class Seleccion extends javax.swing.JFrame {

    /**
     * Constructor que inicializa la ventana.
     */
    public Seleccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btVistaStock = new javax.swing.JButton();
        controlCambiosBT = new javax.swing.JButton();
        btNuevoProducto1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btVistaStock.setBackground(new java.awt.Color(102, 102, 255));
        btVistaStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btVistaStock.setForeground(new java.awt.Color(255, 255, 255));
        btVistaStock.setText("Vista Stock");
        btVistaStock.setMaximumSize(new java.awt.Dimension(131, 27));
        btVistaStock.setPreferredSize(new java.awt.Dimension(131, 27));
        btVistaStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVistaStockActionPerformed(evt);
            }
        });

        controlCambiosBT.setBackground(new java.awt.Color(102, 102, 255));
        controlCambiosBT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        controlCambiosBT.setForeground(new java.awt.Color(255, 255, 255));
        controlCambiosBT.setText("Control de Cambios");
        controlCambiosBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlCambiosBTActionPerformed(evt);
            }
        });

        btNuevoProducto1.setBackground(new java.awt.Color(102, 102, 255));
        btNuevoProducto1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btNuevoProducto1.setForeground(new java.awt.Color(255, 255, 255));
        btNuevoProducto1.setText("Nuevo Producto");
        btNuevoProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoProducto1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btVistaStock, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btNuevoProducto1)
                .addGap(75, 75, 75)
                .addComponent(controlCambiosBT)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVistaStock, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNuevoProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(controlCambiosBT, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVistaStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVistaStockActionPerformed
       vs();
    }//GEN-LAST:event_btVistaStockActionPerformed

    private void controlCambiosBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlCambiosBTActionPerformed
      controlCambios cc=new controlCambios(this,true);
      cc.setLocationRelativeTo(null);
      cc.setVisible(true);
      
    }//GEN-LAST:event_controlCambiosBTActionPerformed

    private void btNuevoProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoProducto1ActionPerformed
        // TODO add your handling code here:
        nuevoProducto();
    }//GEN-LAST:event_btNuevoProducto1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNuevoProducto1;
    private javax.swing.JButton btVistaStock;
    private javax.swing.JButton controlCambiosBT;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */

    /**
     * Método que muestra la ventana de creación de nuevo producto.
     */
    public void nuevoProducto(){
      Vista.nuevoProducto np= new Vista.nuevoProducto(this, true);
        np.setVisible(true);
}

    /**
     * Método que muestra la vista de stock.
     */
    public void vs(){
    Vista.vStock v=new Vista.vStock(this,true);
    v.setLocationRelativeTo(null);
    v.setVisible(true);
}

}